// Tradução gerada por IA — sujeita a revisão nativa. Data: 2026-07-20.
// Français (standard) — dicionário completo tipado a partir de content.pt.
// Invariantes: números, valores R$, unidades (ha, kg, t, sacas), percentuais,
// anos, fontes (IBGE, CONAB, Embrapa, CEPEA, PEVS...), nomes próprios,
// placeholders ({price}, {where}...) e emojis permanecem idênticos ao PT.

import { content } from "./content";

export const contentFr: typeof content.pt = {
  header: {
    navHow: "Comment ça marche",
    navTrust: "Confiance",
    navPricing: "Tarifs",
    cta: "Annoncer ma terre",
  },
  hero: {
    title: "Chaque parcelle de terre en production",
    subtitle:
      "Nous connectons les propriétaires de terres inexploitées à ceux qui veulent les faire produire — avec vérification, contrat et suivi.",
    ctaHave: "J'ai une terre",
    ctaWant: "Je cherche une terre",
    trustLine: "Gratuit jusqu'à la conclusion de l'accord",
    card: {
      photoLabel: "photo aérienne de la ferme",
      name: "Fazenda Boa Vista",
      area: "128 ha",
      location: "Rio Verde, GO",
      verified: "Vérifié",
    },
  },
  how: {
    eyebrow: "Comment ça marche",
    title: "De l'annonce à la signature, en trois étapes",
    steps: [
      {
        title: "Annoncez avec vérification",
        desc: "Documents et données de la terre contrôlés avant publication.",
      },
      {
        title: "Trouvez le partenaire idéal",
        desc: "Producteurs, élevage, solaire et reboisement vous contactent. Vous échangez et comparez.",
      },
      {
        title: "Concluez en toute sécurité",
        desc: "Contrat standardisé, signature électronique et rapports de suivi.",
      },
    ],
  },
  trust: {
    eyebrow: "Confiance",
    title: "Conçu pour sécuriser les deux parties",
    badges: [
      {
        title: "Annonces vérifiées",
        desc: "Chaque terre publiée fait l'objet d'un contrôle des documents et du CAR (registre environnemental rural).",
      },
      {
        title: "Contrats standardisés",
        desc: "Des modèles revus par des avocats spécialisés en droit rural, avec des clauses claires de fermage ou de partenariat.",
      },
      {
        title: "Suivi par satellite",
        desc: "Le propriétaire reçoit des rapports périodiques montrant comment sa terre est utilisée.",
      },
    ],
  },
  appraiser: {
    navLabel: "Estimer ma terre",
    eyebrow: "Calculateur",
    title: "Combien vaut votre terre inexploitée ?",
    subtitle:
      "Découvrez en 1 minute la fourchette de fermage pratiquée dans votre région.",
    stateLabel: "État",
    municipalityLabel: "Municipalité",
    municipalityPlaceholder: "Sélectionnez la municipalité...",
    municipalitySelectState: "Choisissez d'abord l'État",
    municipalityLoading: "Chargement des municipalités...",
    hectaresLabel: "Surface (hectares)",
    hectaresPlaceholder: "Ex. : 128",
    purposeLabel: "Usage de la terre",
    purposePlaceholder: "Sélectionnez l'usage...",
    submit: "Calculer la valeur",
    resultTitle: "Fourchette de référence pour votre terre",
    perHaYear: "par hectare/an",
    totalForArea: "Pour votre surface, environ",
    consultTitle: "Ce marché est très spécifique",
    consultBody:
      "Pour cet usage, les valeurs varient trop d'une région à l'autre pour donner une fourchette fiable. Laissez vos coordonnées et nous vous préviendrons dès qu'il y aura des offres réelles dans votre région.",
    consultPickCrop:
      "Astuce : choisissez la culture spécifique dans le champ ci-dessus — pour plusieurs cultures (banane, açaí, cacao...) nous disposons de références de marché pour votre région.",
    consultPotential:
      "Potentiel de votre surface avec {use} — l'usage le plus valorisé avec référence dans votre région :",
    disclaimer:
      "Valeurs de référence issues de sources publiques du marché (syndicats ruraux, IMEA, CNA, cabinets de conseil). Elles ne constituent pas une expertise formelle — la valeur réelle dépend du sol, de la logistique, de l'eau et de la négociation.",
    legalNote:
      "Selon la loi brésilienne (Estatuto da Terra), le fermage est plafonné à 15% de la valeur du bien par an (30% dans les zones d'exploitation intensive).",
    leadTitle: "Vous voulez recevoir de vraies offres dans cette fourchette ?",
    leadSubtitle: "Rejoignez la liste d'attente — c'est gratuit.",
    heroLink: "Combien vaut ma terre ?",
    heroLinkSub: "Découvrez-le en 30 secondes — gratuit, avec des données officielles.",
    compareTitle: "Autres usages dans votre région",
    compareUnit: "/ha/an",
    compareYourChoice: "votre choix",
    compareUpsell:
      "Dans votre région, les terres destinées à {use} se louent jusqu'à {ratio}x la valeur de votre choix actuel.",
    compareCaveat:
      "Cette comparaison utilise des fourchettes régionales de marché. La viabilité d'un usage plus valorisé sur votre terre dépend du sol, du relief, de l'eau et de la logistique — Palmo peut vous aider à le vérifier.",
    selectiveTag: "marché sélectif — dépend des projets et du réseau électrique de la région",
    cropLabel: "Culture spécifique (optionnel)",
    cropPlaceholder: "Toutes / je ne sais pas encore",
    cropRefPotential:
      "Estimation basée sur la valeur de marché de {source} — R$ {landMin} à {landMax} mille/ha — convertie à 2,5–6% par an :",
    formedPotential:
      "Avec une plantation FORMÉE et en production : dans votre région, les fermages se situent généralement autour de ~15% du chiffre d'affaires ({source}) :",
    formedNote:
      "Valable pour une culture déjà plantée et en production. La terre nue (sans la plantation) vaut bien moins — voir ci-dessous.",
    formedMath:
      "🧮 Le calcul : chiffre d'affaires estimé de {revMin} à {revMax} par hectare/an × ~15% (usage de marché pour une culture formée) = la fourchette ci-dessus.",
    nationalFallbackNote:
      "⚠️ Référence nationale large — votre État n'a pas encore de fourchette propre relevée pour cet usage ; considérez-la comme un plancher et un plafond larges.",
    cropVariants: {
      cafe: [
        { value: "arabica", label: "Arabica" },
        { value: "conilon", label: "Conilon / robusta" },
      ],
      uva: [
        { value: "mesa", label: "Raisin de table" },
        { value: "vinho_suco", label: "Vin et jus" },
      ],
      banana: [
        { value: "prata", label: "Prata" },
        { value: "nanica", label: "Cavendish (nanica)" },
        { value: "terra", label: "Banane plantain" },
      ],
    },
    variantLabel: "Variété (optionnel)",
    variantPlaceholder: "Toutes / je ne sais pas",
    pevsPriceLine:
      "💰 Prix moyen payé au producteur {where} : {price}/kg (IBGE PEVS {year}).",
    pevsWhereMuni: "dans votre municipalité",
    pevsWhereUf: "dans votre État",
    pevsWhereBr: "au Brésil",
    pevsHint:
      "Revenu sur pied = densité de votre peuplement × production × ce prix. Et la PGPM-Bio (CONAB) garantit un prix minimum — en cas de vente sous le plancher, la CONAB paie la différence.",
    rawLandLabel: "Terre nue (sans plantation formée) :",
    advantageLabel: "Avantage régional",
    vtnPotential:
      "Estimation à partir de la valeur officielle de la terre dans votre municipalité (VTN {year} de la Receita Federal × 2,5–6% par an) :",
    vtnPotentialApprox:
      "Votre municipalité n'a pas déclaré de VTN à la Receita Federal. Estimation à partir de la moyenne officielle de votre État (VTN {year} × 2,5–6% par an) :",
    vtnLine:
      "Valeur officielle de la terre (VTN {year}, Receita Federal) dans votre municipalité : {value}/ha.",
    vtnLineApprox:
      "Moyenne officielle de la terre dans votre État (VTN {year}, Receita Federal) : {value}/ha — votre municipalité n'a pas déclaré de valeur propre.",
    crops: {
      graos: [
        { value: "soja", label: "Soja" },
        { value: "milho", label: "Maïs" },
        { value: "algodao", label: "Coton" },
        { value: "arroz", label: "Riz irrigué" },
        { value: "feijao", label: "Haricot" },
        { value: "sorgo", label: "Sorgho" },
        { value: "trigo", label: "Blé" },
        { value: "girassol", label: "Tournesol" },
        { value: "amendoim", label: "Arachide" },
        { value: "gergelim", label: "Sésame" },
        { value: "aveia", label: "Avoine" },
        { value: "cevada", label: "Orge" },
        { value: "canola", label: "Colza (canola)" },
        { value: "milheto", label: "Mil (millet perlé)" },
        { value: "grao_de_bico", label: "Pois chiche" },
        { value: "mamona", label: "Ricin" },
        { value: "fumo", label: "Tabac" },
        { value: "fava", label: "Fève" },
        { value: "chia", label: "Chia" },
        { value: "triticale", label: "Triticale" },
      ],
      lavoura_permanente: [
        { value: "cafe", label: "Café" },
        { value: "cacau", label: "Cacao" },
        { value: "caju", label: "Cajou (noix)" },
        { value: "citros", label: "Agrumes (orange)" },
        { value: "seringueira", label: "Hévéa" },
        { value: "dende", label: "Palmier à huile" },
        { value: "erva_mate", label: "Yerba maté" },
        { value: "pimenta_do_reino", label: "Poivre noir" },
        { value: "guarana", label: "Guarana" },
        { value: "macadamia", label: "Macadamia" },
        { value: "noz_pecan", label: "Noix de pécan" },
        { value: "oliveira", label: "Olivier (huile)" },
        { value: "palmito_pupunha", label: "Cœur de palmier pupunha" },
        { value: "urucum", label: "Roucou (urucum)" },
        { value: "limao_tahiti", label: "Citron vert Tahiti" },
        { value: "aroeira", label: "Poivre rose (aroeira)" },
      ],
      fruticultura: [
        { value: "banana", label: "Banane" },
        { value: "manga", label: "Mangue" },
        { value: "uva", label: "Raisin" },
        { value: "melao", label: "Melon" },
        { value: "acai", label: "Açaí" },
        { value: "coco", label: "Noix de coco" },
        { value: "mamao", label: "Papaye" },
        { value: "maracuja", label: "Fruit de la passion" },
        { value: "melancia", label: "Pastèque" },
        { value: "abacaxi", label: "Ananas" },
        { value: "goiaba", label: "Goyave" },
        { value: "acerola", label: "Acérola" },
        { value: "abacate", label: "Avocat" },
        { value: "atemoia", label: "Pomme cannelle et atémoya" },
        { value: "graviola", label: "Corossol" },
        { value: "pitaya", label: "Pitaya (fruit du dragon)" },
        { value: "morango", label: "Fraise" },
        { value: "maca", label: "Pomme" },
        { value: "pessego", label: "Pêche" },
        { value: "tangerina", label: "Mandarine" },
        { value: "cupuacu", label: "Cupuaçu" },
        { value: "roma", label: "Grenade" },
        { value: "lichia", label: "Litchi" },
        { value: "figo", label: "Figue" },
        { value: "caqui", label: "Kaki" },
        { value: "jabuticaba", label: "Jabuticaba" },
      ],
      horticultura: [
        { value: "hortalicas", label: "Légumes en général" },
        { value: "mandioca", label: "Manioc" },
        { value: "batata", label: "Pomme de terre" },
        { value: "batata_doce", label: "Patate douce" },
        { value: "tomate", label: "Tomate" },
        { value: "cebola", label: "Oignon" },
        { value: "alho", label: "Ail" },
        { value: "cenoura", label: "Carotte" },
        { value: "abobora", label: "Courge" },
        { value: "pimentao", label: "Poivron" },
        { value: "inhame", label: "Igname" },
        { value: "quiabo", label: "Gombo" },
        { value: "gengibre", label: "Gingembre" },
        { value: "pimentas", label: "Piments (conserves)" },
        { value: "mandioquinha", label: "Arracacha (mandioquinha)" },
        { value: "brassicas", label: "Brassicacées (chou, brocoli...)" },
        { value: "beterraba", label: "Betterave" },
        { value: "chuchu", label: "Chayotte" },
        { value: "pepino", label: "Concombre" },
        { value: "flores", label: "Fleurs et plantes ornementales" },
      ],
      pecuaria_corte: [
        { value: "bovinos_corte", label: "Bovins de boucherie" },
        { value: "ovinos", label: "Ovins (moutons)" },
        { value: "caprinos", label: "Caprins (chèvres)" },
        { value: "bufalos", label: "Buffles" },
      ],
      pecuaria_leite: [
        { value: "bovino_leite", label: "Bovins laitiers" },
        { value: "caprino_leite", label: "Chèvres laitières" },
      ],
      avicultura_suinocultura: [
        { value: "frango_corte", label: "Poulet de chair (intégration)" },
        { value: "postura", label: "Poules pondeuses (œufs)" },
        { value: "suinos", label: "Porcs (intégration)" },
      ],
      aquicultura: [
        { value: "tilapia", label: "Tilapia" },
        { value: "camarao", label: "Crevette (élevage)" },
        { value: "tambaqui", label: "Tambaqui" },
        { value: "pirarucu", label: "Pirarucu" },
      ],
      silvicultura: [
        { value: "eucalipto", label: "Eucalyptus" },
        { value: "pinus", label: "Pin" },
        { value: "teca", label: "Teck" },
        { value: "mogno_africano", label: "Acajou africain" },
        { value: "acacia_negra", label: "Acacia noir (tanin)" },
        { value: "parica", label: "Paricá" },
        { value: "cedro_australiano", label: "Cèdre australien" },
        { value: "bambu", label: "Bambou" },
      ],
      extrativismo: [
        { value: "carnauba", label: "Carnaúba (poudre et cire)" },
        { value: "babacu", label: "Babaçu" },
        { value: "pinhao", label: "Pignon d'araucaria (pinhão)" },
        { value: "castanha_amazonia", label: "Noix du Brésil" },
        { value: "piacava", label: "Piaçava (fibre)" },
        { value: "pequi", label: "Pequi" },
        { value: "mangaba", label: "Mangaba" },
        { value: "licuri", label: "Licuri" },
        { value: "umbu", label: "Umbu" },
        { value: "baru", label: "Baru" },
      ],
    },
    cropNotes: {
      soja: "Les contrats céréaliers sont généralement fixés en sacas de soja par hectare/an.",
      milho: "Même pour le maïs, les contrats sont habituellement fixés en sacas de soja par hectare/an (rotation soja/maïs).",
      algodao: "Les surfaces aptes au coton se négocient généralement en haut de la fourchette céréalière de la région.",
      arroz: "Le riz irrigué a son propre marché : généralement 18–25 sacas de riz/ha/an pour la terre et l'eau (référence RS).",
      cafe: "Le café se négocie généralement en partenariat (métayage), pas en loyer fixe — et ce sont deux marchés aux prix très différents : arabica (MG/SP) et conilon/robusta (ES/RO). Indiquez la variété ci-dessus pour de meilleures données.",
      cacau: "Le cacao se négocie généralement en partenariat, avec partage de la production — les loyers fixes par hectare sont rares.",
      banana: "Une bananeraie formée se loue en fraction du chiffre d'affaires (~15%) ; la terre nue pour planter la banane vaut bien moins et dépend de l'eau.",
      manga: "Un verger de manguiers formé (Vale do São Francisco) se loue en fraction du chiffre d'affaires — le prix du fruit est très volatil.",
      uva: "Un vignoble formé de raisin de table irrigué a un chiffre d'affaires élevé et des coûts élevés ; le fermage est généralement une fraction du chiffre d'affaires.",
      melao: "Le melon est une culture annuelle : dans le pôle Mossoró/Açu (RN/CE), des entreprises louent la terre nue par campagne — la terre irriguée avec droit d'eau vaut une prime.",
      acai: "L'açaí planté en terre ferme se loue en fraction du chiffre d'affaires ; l'açaí de plaine inondable géré est un marché extractif à part.",
      coco: "Une cocoteraie naine formée et irriguée se loue en fraction du chiffre d'affaires ; la cocoteraie géante pluviale rapporte bien moins.",
      mamao: "La papaye a un cycle court (~2 ans) : la plantation formée se loue en fraction du chiffre d'affaires, généralement par cycle.",
      maracuja: "Le fruit de la passion a un cycle de 1,5–2 ans : le partenariat ou la location par cycle, en fraction du chiffre d'affaires, est la norme.",
      caju: "La cajouraie traditionnelle rapporte peu (300–500 kg/ha de noix) ; renouvelée avec des clones Embrapa, elle atteint 1.600 kg/ha — le partenariat de renouvellement de vieilles cajouraies est un marché actif dans le CE/PI/RN.",
      mandioca: "Le manioc est une culture annuelle : féculeries et fermiers le plantent en renouvellement de pâturage (SP/PR) ; dans le Nordeste, la production familiale de farine domine.",
      melancia: "La pastèque est une culture de campagne : la terre nue se loue par cycle — Teixeira de Freitas (BA) récolte 59–71 t/ha (CEPEA).",
      abacaxi: "L'ananas a un cycle d'environ 18 mois ; la location par cycle est la norme, avec une prime pour les surfaces irriguées.",
      ovinos: "Dans le semi-aride, le pâturage natif (caatinga) se loue bien moins cher que le pâturage formé ; les contrats par tête/mois sont courants.",
      caprinos: "Les caprins dominent la caatinga : contrats par tête/mois ou fraction du pâturage ; le pâturage formé vaut plus que le natif.",
      bufalos: "Les buffles se concentrent dans les plaines inondables et les bas-fonds (Marajó/PA) ; le fermage suit le marché du pâturage de la région.",
      frango_corte: "Dans l'intégration, c'est le lot logé qui rémunère : le poulailler formé est l'actif qui se loue — la terre nue pèse peu.",
      suinos: "L'élevage porcin intégré rémunère par lot ; l'installation formée est l'actif pertinent, pas la terre nue.",
      tilapia: "L'aquaculture loue la surface en eau : un réservoir ou un bassin creusé formé a son propre marché (R$/ha d'eau), distinct de la terre sèche.",
      camarao: "Un bassin à crevettes formé (RN/CE) se loue cher ; la terre nue apte à la crevetticulture dépend de la licence et de l'eau saumâtre.",
      eucalipto: "Les forêts plantées utilisent des contrats longs (7+ ans) : fermage fixe ou partenariat forestier avec l'industrie.",
      erva_mate: "Un peuplement de yerba maté formé se loue généralement par récolte — marché traditionnel du Sud (PR/SC/RS).",
      fumo: "Le tabac fonctionne par intégration avec les manufactures : l'entreprise finance les intrants et achète la récolte — le partenariat foncier classique du Sud, avec un revenu moyen d'environ R$46k/ha pour le producteur (Afubra/CONAB, campagne 24/25).",
      mamona: "Le ricin est une culture pluviale du semi-aride (BA en tête) ; souvent en association avec le haricot — location par campagne.",
      limao_tahiti: "Le citron vert Tahiti a son propre marché et son indicateur CEPEA (SP domine) ; prix fortement saisonnier — le verger formé se loue en fraction du chiffre d'affaires.",
      gengibre: "Le gingembre est une culture annuelle d'exportation (ES/SC/PR) : la terre nue se loue par campagne, avec une prime pour sol léger et eau.",
      flores: "La floriculture loue la STRUCTURE : la serre formée a son propre marché (Holambra/SP et les montagnes du CE), distinct de la terre nue.",
      acacia_negra: "L'acacia noir (RS) est une forêt à cycle d'environ 7 ans dont l'écorce se vend pour le tanin — contrats avec l'industrie, comme l'eucalyptus.",
      pirarucu: "Le pirarucu exige de grands bassins et une licence ; le RO/AM mènent l'élevage (Embrapa) — l'actif qui se loue est le bassin formé.",
      carnauba: "Une palmeraie native de carnaúba sur pied rapporte déjà : le PI et le CE concentrent ~96% de la poudre de carnaúba du pays, 100% nordestine (IBGE PEVS) — l'extraction se loue par saison de paille.",
      babacu: "Le MA représente ~94% des amandes de babaçu (IBGE PEVS) ; attention à la loi du Babaçu Libre dans plusieurs municipalités — l'accès des casseuses est protégé.",
      pinhao: "Le Sud concentre ~97% du pinhão national (IBGE PEVS) : les araucarias natifs sur pied rapportent par récolte — l'abattage est interdit, le revenu vient de la cueillette.",
      castanha_amazonia: "L'AC mène la noix du Brésil, avec l'AM et le PA sur le podium (IBGE PEVS) : les châtaigneraies natives rapportent par saison — l'abattage de l'arbre est interdit par la loi. Plancher PGPM-Bio 2024 : R$3,66/kg (CONAB).",
      piacava: "Le BA concentre ~96% de la piaçava du pays — Ilhéus, Nilo Peçanha et Cairu en tête (IBGE PEVS) ; les peuplements natifs se louent par coupe de fibre.",
      pequi: "Le pequi est un revenu sur pied du cerrado (GO/MG/TO dans la PEVS/IBGE) : cueillette par saison dans les peuplements natifs — l'abattage de l'arbre est restreint par la loi dans le GO/MG.",
      mangaba: "La mangaba est un extractivisme du littoral du Nordeste (le SE est la référence dans la PEVS/IBGE) ; les peuplements natifs rapportent par saison.",
      licuri: "Le licuri est le palmier du semi-aride bahianais (PEVS/IBGE) : amandes cueillies dans les peuplements natifs — revenu sur pied typique de la caatinga.",
      umbu: "L'umbu est une cueillette de la caatinga (BA en tête dans la PEVS/IBGE) : les arbres natifs rapportent par saison pour la pulpe et les confiseries.",
      baru: "Le baru est la noix du cerrado en expansion (GO/MG/MT) : cueillette sur arbres natifs et premières plantations — marché acheteur en croissance.",
    },
    cropFormation: {
      banana: "De la plantation à la première récolte : ~10–14 mois (Embrapa).",
      mamao: "De la plantation à la première récolte : ~8–10 mois (Embrapa).",
      maracuja: "De la plantation à la première récolte : ~7–9 mois (Embrapa).",
      uva: "De la plantation à la première récolte : ~1,5 an ; pleine production : ~3 ans (Embrapa).",
      cafe: "De la plantation à la première récolte : ~2–3 ans ; pleine production : ~4–5 ans (Embrapa) — les contrats de plantation prévoient généralement une période de grâce.",
      caju: "Cajou nain clonal : première récolte ~2–3 ans ; pleine production : ~7 ans (Embrapa) — les contrats de plantation prévoient généralement une période de grâce.",
      coco: "Cocotier nain : première récolte ~2,5–3 ans ; pleine production : ~6 ans (Embrapa) — les contrats de plantation prévoient généralement une période de grâce.",
      acai: "Açaí de terre ferme : première récolte ~3 ans ; pleine production : ~5–6 ans (Embrapa) — les contrats de plantation prévoient généralement une période de grâce.",
      cacau: "De la plantation à la première récolte : ~3–4 ans ; pleine production : ~6–7 ans (Embrapa/CEPLAC) — les contrats de plantation prévoient généralement une période de grâce.",
      citros: "De la plantation à la première récolte : ~3 ans ; pleine production : ~7–8 ans (Embrapa/Fundecitrus) — les contrats de plantation prévoient généralement une période de grâce.",
      manga: "Manguier greffé : première récolte ~3–4 ans ; pleine production : ~7 ans (Embrapa) — les contrats de plantation prévoient généralement une période de grâce.",
      dende: "De la plantation à la première récolte : ~3 ans ; pleine production : ~7–8 ans (Embrapa) — les intégrateurs structurent généralement la période de grâce.",
      seringueira: "De la plantation au début de la saignée : ~6–7 ans (Embrapa) — les contrats de plantation prévoient généralement une longue période de grâce.",
      erva_mate: "De la plantation à la première taille commerciale : ~4–5 ans (Embrapa Florestas).",
      eucalipto: "De la plantation à la coupe : ~6–7 ans (Embrapa Florestas) — c'est pourquoi les contrats forestiers sont longs.",
      goiaba: "La goyave clonale produit à partir de ~1,5–2 ans ; pleine production : ~4 ans (Embrapa).",
      abacate: "De la plantation à la première récolte : ~3–4 ans ; pleine production : ~7 ans (Embrapa) — les contrats de plantation prévoient généralement une période de grâce.",
      maca: "De la plantation à la première récolte : ~3–4 ans ; pleine production : ~5–6 ans (Epagri/Embrapa) — les contrats de plantation prévoient généralement une période de grâce.",
      pessego: "De la plantation à la première récolte : ~2–3 ans ; pleine production : ~4–5 ans (Embrapa).",
    },
  },
  auth: {
    signIn: "Se connecter",
    signInGoogle: "Se connecter avec Google",
    signOut: "Se déconnecter",
    myAccount: "Mon compte",
    accountTitle: "Mon compte",
    accountSubtitle: "Votre compte Palmo. Bientôt : vos annonces et vos offres.",
    notSignedIn: "Vous n'êtes pas encore connecté. Connectez-vous pour enregistrer vos données et suivre vos annonces.",
    signedInAs: "Connecté en tant que",
  },
  pricing: {
    eyebrow: "Tarifs",
    title: "Des tarifs transparents",
    subtitle:
      "Vous ne payez que lorsqu'un accord est conclu. Sans abonnement et sans frais d'annonce.",
    tiers: [
      {
        name: "Annoncer et rechercher",
        price: "Gratuit",
        desc: "Publiez votre terre, consultez les annonces, échangez et négociez. Gratuit pour les deux parties.",
      },
      {
        name: "Commission de succès",
        price: "5%",
        priceNote: "de la 1re année de contrat",
        desc: "Facturée uniquement à la signature et payée par celui qui exploitera la terre. Inclut le contrat standardisé, la vérification et la signature électronique.",
        highlight: true,
      },
      {
        name: "Suivi par satellite",
        price: "Abonnement mensuel",
        desc: "Pour que le propriétaire suive l'utilisation de sa terre, grâce aux images satellite de Hexagon. Résiliable à tout moment.",
      },
    ],
    footnote: "Pas de frais cachés. Le propriétaire ne paie jamais pour annoncer.",
  },
  waitlist: {
    eyebrow: "Soyez parmi les premiers",
    title: "Rejoignez la liste d'attente",
    subtitle:
      "Nous vous préviendrons sur WhatsApp dès que Palmo ouvrira dans votre région.",
    nameLabel: "Nom",
    namePlaceholder: "Votre nom complet",
    phoneLabel: "WhatsApp",
    phonePlaceholder: "+55 00 00000-0000",
    countryLabel: "Pays",
    stateLabel: "État",
    statePlaceholder: "Ex. : Bahia",
    municipalityLabel: "Municipalité",
    municipalityPlaceholder: "Ex. : Salvador",
    roleLabel: "Vous êtes...",
    rolePlaceholder: "Sélectionnez...",
    roleHave: "J'ai une terre",
    roleWant: "Je cherche une terre",
    purposeLabel: "Usage prévu de la terre",
    purposePlaceholder: "Sélectionnez l'usage...",
    purposeOptions: [
      { value: "graos", label: "Céréales et oléagineux (soja, maïs, coton...)" },
      { value: "cana", label: "Canne à sucre" },
      { value: "lavoura_permanente", label: "Cultures pérennes (café, agrumes, cacao...)" },
      { value: "fruticultura", label: "Arboriculture fruitière" },
      { value: "horticultura", label: "Horticulture et légumes" },
      { value: "pecuaria_corte", label: "Élevage bovin (viande)" },
      { value: "pecuaria_leite", label: "Élevage laitier" },
      { value: "avicultura_suinocultura", label: "Aviculture / élevage porcin" },
      { value: "aquicultura", label: "Aquaculture" },
      { value: "silvicultura", label: "Sylviculture (eucalyptus, pin...)" },
      { value: "reflorestamento_carbono", label: "Reboisement / crédit carbone" },
      { value: "energia_solar", label: "Énergie solaire" },
      { value: "energia_eolica", label: "Énergie éolienne" },
      { value: "extrativismo", label: "Extractivisme (revenu sur pied)" },
      { value: "outro", label: "Autre" },
    ],
    submit: "Je veux rejoindre la liste",
    submitting: "Envoi en cours...",
    success: "Bien reçu ! Nous vous contacterons sur WhatsApp.",
    error: "Une erreur est survenue. Réessayez dans quelques instants.",
  },
  footer: {
    tagline: "De palmo em palmo, a terra volta a produzir.",
    whatsapp: "Discuter sur WhatsApp",
    instagram: "Instagram",
    rights: "© 2026 Palmo. Fait au Brésil.",
    terms: "Conditions",
    privacy: "Confidentialité",
  },
};
