// Tradução gerada por IA — sujeita a revisão nativa. Data: 2026-07-20.
// 中文（简体）— dicionário completo tipado a partir de content.pt.
// Invariantes: números, valores R$, unidades (ha, kg, t, sacas), percentuais,
// anos, fontes (IBGE, CONAB, Embrapa, CEPEA, PEVS...), nomes próprios,
// placeholders ({price}, {where}...) e emojis permanecem idênticos ao PT.

import { content } from "./content";

export const contentZh: typeof content.pt = {
  header: {
    navHow: "运作方式",
    navTrust: "信任保障",
    navPricing: "价格",
    cta: "发布我的土地",
  },
  hero: {
    title: "让每一寸土地都在生产",
    subtitle:
      "我们将闲置土地的所有者与希望在土地上生产的人连接起来——经过核验、签订合同并持续跟踪。",
    ctaHave: "我有土地",
    ctaWant: "我在找土地",
    trustLine: "成交前完全免费",
    card: {
      photoLabel: "农场航拍照片",
      name: "Fazenda Boa Vista",
      area: "128 ha",
      location: "Rio Verde, GO",
      verified: "已核验",
    },
  },
  how: {
    eyebrow: "运作方式",
    title: "从发布到签约，只需三步",
    steps: [
      {
        title: "发布并核验",
        desc: "土地文件与数据在发布前逐一核对。",
      },
      {
        title: "找到理想的合作伙伴",
        desc: "种植户、畜牧、光伏与再造林项目会主动联系您。您可以沟通并比较。",
      },
      {
        title: "安全成交",
        desc: "标准化合同、电子签名以及后续跟踪报告。",
      },
    ],
  },
  trust: {
    eyebrow: "信任保障",
    title: "为双方提供安全保障",
    badges: [
      {
        title: "核验过的地块信息",
        desc: "每一块发布的土地都经过文件与 CAR（农村环境登记）核查。",
      },
      {
        title: "标准化合同",
        desc: "由农业领域律师审阅的合同范本，租赁或合作条款清晰明确。",
      },
      {
        title: "卫星跟踪",
        desc: "土地所有者定期收到报告，了解土地的实际使用情况。",
      },
    ],
  },
  appraiser: {
    navLabel: "土地估值",
    eyebrow: "计算器",
    title: "您的闲置土地值多少钱？",
    subtitle: "1 分钟内了解您所在地区的土地租赁价格区间。",
    stateLabel: "州（UF）",
    municipalityLabel: "市镇",
    municipalityPlaceholder: "请选择市镇...",
    municipalitySelectState: "请先选择州",
    municipalityLoading: "正在加载市镇列表...",
    hectaresLabel: "面积（ha）",
    hectaresPlaceholder: "例如：128",
    purposeLabel: "土地用途",
    purposePlaceholder: "请选择用途...",
    submit: "计算价值",
    resultTitle: "您土地的参考价格区间",
    perHaYear: "每公顷/年",
    totalForArea: "按您的面积计算，大约为",
    consultTitle: "这一市场非常特殊",
    consultBody:
      "对于这种用途，各地区价格差异过大，无法给出可靠区间。请留下联系方式，一旦您所在地区出现真实报价，我们会通知您。",
    consultPickCrop:
      "提示：请在上方选择具体作物——对多种作物（香蕉、阿萨伊果 açaí、可可等）我们有您所在地区的市场参考。",
    consultPotential:
      "您的土地用于 {use} 的潜力——这是您所在地区有参考数据的最高价值用途：",
    disclaimer:
      "参考价格基于公开市场来源（农村工会、IMEA、CNA 及咨询机构）。不构成正式估值——实际价值取决于土壤、物流、水源与谈判。",
    legalNote:
      "根据巴西《土地法》（Estatuto da Terra），土地租金每年不得超过地产价值的 15%（集约经营区为 30%）。",
    leadTitle: "想收到该区间的真实报价吗？",
    leadSubtitle: "加入候补名单——完全免费。",
    heroLink: "我的土地值多少钱？",
    heroLinkSub: "30 秒了解——免费，基于官方数据。",
    compareTitle: "您所在地区的其他用途",
    compareUnit: "/ha/年",
    compareYourChoice: "您的选择",
    compareUpsell:
      "在您所在的地区，用于 {use} 的土地租金最高可达您当前选择的 {ratio} 倍。",
    compareCaveat:
      "该比较基于地区市场区间。更高价值的用途是否适合您的土地，取决于土壤、地形、水源与物流——Palmo 可以帮您核实。",
    selectiveTag: "选择性市场——取决于项目和该地区的电网条件",
    cropLabel: "具体作物（可选）",
    cropPlaceholder: "全部 / 尚不确定",
    cropRefPotential:
      "根据 {source} 的市场价值估算——R$ {landMin} 至 {landMax} 千/ha——按每年 2,5–6% 折算：",
    formedPotential:
      "已成园并投产的种植园：在您所在地区，租金通常约为营业收入的 ~15%（{source}）：",
    formedNote:
      "适用于已种植并投产的园地。裸地（未成园）的价值低得多——见下文。",
    formedMath:
      "🧮 计算方式：估算每公顷/年收入 {revMin} 至 {revMax} × ~15%（成园作物的市场惯例）= 上方区间。",
    nationalFallbackNote:
      "⚠️ 全国性宽泛参考——您所在的州尚无该用途的专门调查区间；请将其视为较宽的下限与上限。",
    cropVariants: {
      cafe: [
        { value: "arabica", label: "阿拉比卡" },
        { value: "conilon", label: "科尼隆 / 罗布斯塔" },
      ],
      uva: [
        { value: "mesa", label: "鲜食葡萄" },
        { value: "vinho_suco", label: "酿酒与果汁葡萄" },
      ],
      banana: [
        { value: "prata", label: "Prata（普拉塔蕉）" },
        { value: "nanica", label: "香芽蕉（Nanica）" },
        { value: "terra", label: "大蕉（Da terra）" },
      ],
    },
    variantLabel: "品种（可选）",
    variantPlaceholder: "全部 / 不确定",
    pevsPriceLine:
      "💰 {where}支付给生产者的平均价格：{price}/kg（IBGE PEVS {year}）。",
    pevsWhereMuni: "在您的市镇",
    pevsWhereUf: "在您所在的州",
    pevsWhereBr: "在巴西全国",
    pevsHint:
      "立木收入 = 您林地的密度 × 产量 × 该价格。PGPM-Bio（CONAB）保障最低价——若售价低于底价，CONAB 将补足差额。",
    rawLandLabel: "裸地（未成园）：",
    advantageLabel: "地区优势",
    vtnPotential:
      "按您市镇的官方地价估算（Receita Federal 联邦税务局的 VTN {year} × 每年 2,5–6%）：",
    vtnPotentialApprox:
      "您的市镇未向 Receita Federal 申报 VTN。按您所在州的官方平均值估算（VTN {year} × 每年 2,5–6%）：",
    vtnLine:
      "您市镇的官方地价（VTN {year}，Receita Federal）：{value}/ha。",
    vtnLineApprox:
      "您所在州的官方平均地价（VTN {year}，Receita Federal）：{value}/ha——您的市镇未申报自己的数值。",
    crops: {
      graos: [
        { value: "soja", label: "大豆" },
        { value: "milho", label: "玉米" },
        { value: "algodao", label: "棉花" },
        { value: "arroz", label: "灌溉水稻" },
        { value: "feijao", label: "菜豆" },
        { value: "sorgo", label: "高粱" },
        { value: "trigo", label: "小麦" },
        { value: "girassol", label: "向日葵" },
        { value: "amendoim", label: "花生" },
        { value: "gergelim", label: "芝麻" },
        { value: "aveia", label: "燕麦" },
        { value: "cevada", label: "大麦" },
        { value: "canola", label: "油菜（卡诺拉）" },
        { value: "milheto", label: "珍珠粟" },
        { value: "grao_de_bico", label: "鹰嘴豆" },
        { value: "mamona", label: "蓖麻" },
        { value: "fumo", label: "烟草" },
        { value: "fava", label: "蚕豆" },
        { value: "chia", label: "奇亚籽" },
        { value: "triticale", label: "小黑麦" },
      ],
      lavoura_permanente: [
        { value: "cafe", label: "咖啡" },
        { value: "cacau", label: "可可" },
        { value: "caju", label: "腰果" },
        { value: "citros", label: "柑橘（橙）" },
        { value: "seringueira", label: "橡胶树" },
        { value: "dende", label: "油棕" },
        { value: "erva_mate", label: "马黛茶（erva-mate）" },
        { value: "pimenta_do_reino", label: "黑胡椒" },
        { value: "guarana", label: "瓜拉纳（guaraná）" },
        { value: "macadamia", label: "澳洲坚果" },
        { value: "noz_pecan", label: "碧根果（美洲山核桃）" },
        { value: "oliveira", label: "油橄榄" },
        { value: "palmito_pupunha", label: "桃棕榈笋（pupunha）" },
        { value: "urucum", label: "胭脂树（urucum）" },
        { value: "limao_tahiti", label: "塔希提青柠" },
        { value: "aroeira", label: "粉红胡椒（aroeira）" },
      ],
      fruticultura: [
        { value: "banana", label: "香蕉" },
        { value: "manga", label: "芒果" },
        { value: "uva", label: "葡萄" },
        { value: "melao", label: "甜瓜" },
        { value: "acai", label: "阿萨伊果（açaí）" },
        { value: "coco", label: "椰子" },
        { value: "mamao", label: "木瓜" },
        { value: "maracuja", label: "百香果" },
        { value: "melancia", label: "西瓜" },
        { value: "abacaxi", label: "菠萝" },
        { value: "goiaba", label: "番石榴" },
        { value: "acerola", label: "针叶樱桃（acerola）" },
        { value: "abacate", label: "牛油果" },
        { value: "atemoia", label: "番荔枝与阿蒂莫耶" },
        { value: "graviola", label: "刺果番荔枝" },
        { value: "pitaya", label: "火龙果" },
        { value: "morango", label: "草莓" },
        { value: "maca", label: "苹果" },
        { value: "pessego", label: "桃" },
        { value: "tangerina", label: "柑橘（橘）" },
        { value: "cupuacu", label: "Cupuaçu（古布阿苏）" },
        { value: "roma", label: "石榴" },
        { value: "lichia", label: "荔枝" },
        { value: "figo", label: "无花果" },
        { value: "caqui", label: "柿子" },
        { value: "jabuticaba", label: "Jabuticaba（嘉宝果）" },
      ],
      horticultura: [
        { value: "hortalicas", label: "各类蔬菜" },
        { value: "mandioca", label: "木薯" },
        { value: "batata", label: "马铃薯" },
        { value: "batata_doce", label: "甘薯" },
        { value: "tomate", label: "番茄" },
        { value: "cebola", label: "洋葱" },
        { value: "alho", label: "大蒜" },
        { value: "cenoura", label: "胡萝卜" },
        { value: "abobora", label: "南瓜" },
        { value: "pimentao", label: "甜椒" },
        { value: "inhame", label: "山药（inhame）" },
        { value: "quiabo", label: "秋葵" },
        { value: "gengibre", label: "生姜" },
        { value: "pimentas", label: "辣椒（加工用）" },
        { value: "mandioquinha", label: "秘鲁胡萝卜（mandioquinha）" },
        { value: "brassicas", label: "十字花科（卷心菜、西兰花等）" },
        { value: "beterraba", label: "甜菜根" },
        { value: "chuchu", label: "佛手瓜" },
        { value: "pepino", label: "黄瓜" },
        { value: "flores", label: "花卉与观赏植物" },
      ],
      pecuaria_corte: [
        { value: "bovinos_corte", label: "肉牛" },
        { value: "ovinos", label: "绵羊" },
        { value: "caprinos", label: "山羊" },
        { value: "bufalos", label: "水牛" },
      ],
      pecuaria_leite: [
        { value: "bovino_leite", label: "奶牛" },
        { value: "caprino_leite", label: "奶山羊" },
      ],
      avicultura_suinocultura: [
        { value: "frango_corte", label: "肉鸡（一体化养殖）" },
        { value: "postura", label: "蛋鸡" },
        { value: "suinos", label: "生猪（一体化养殖）" },
      ],
      aquicultura: [
        { value: "tilapia", label: "罗非鱼" },
        { value: "camarao", label: "对虾养殖" },
        { value: "tambaqui", label: "塔姆巴基鱼（tambaqui）" },
        { value: "pirarucu", label: "巨骨舌鱼（pirarucu）" },
      ],
      silvicultura: [
        { value: "eucalipto", label: "桉树" },
        { value: "pinus", label: "松树" },
        { value: "teca", label: "柚木" },
        { value: "mogno_africano", label: "非洲桃花心木" },
        { value: "acacia_negra", label: "黑荆树（单宁）" },
        { value: "parica", label: "Paricá（帕里卡）" },
        { value: "cedro_australiano", label: "澳洲红雪松" },
        { value: "bambu", label: "竹子" },
      ],
      extrativismo: [
        { value: "carnauba", label: "Carnaúba（卡尔纳乌巴棕榈，粉与蜡）" },
        { value: "babacu", label: "Babaçu（巴巴苏棕榈）" },
        { value: "pinhao", label: "南洋杉松子（pinhão）" },
        { value: "castanha_amazonia", label: "巴西坚果" },
        { value: "piacava", label: "Piaçava（皮阿萨瓦纤维）" },
        { value: "pequi", label: "Pequi（佩基果）" },
        { value: "mangaba", label: "Mangaba（曼加巴果）" },
        { value: "licuri", label: "Licuri（利库里棕榈）" },
        { value: "umbu", label: "Umbu（乌姆布果）" },
        { value: "baru", label: "Baru（巴鲁坚果）" },
      ],
    },
    cropNotes: {
      soja: "谷物合同通常按每公顷/年若干袋（sacas）大豆计价。",
      milho: "即使是玉米，合同通常也按每公顷/年的大豆袋数（sacas）计价（大豆/玉米轮作）。",
      algodao: "适合棉花的地块通常按该地区谷物价格区间的上限成交。",
      arroz: "灌溉水稻有独立市场：土地加水权通常为 18–25 袋（sacas）稻谷/ha/年（RS 参考）。",
      cafe: "咖啡通常以合作分成（对半分成）方式谈判，而非固定租金——且这是价格差异很大的两个市场：阿拉比卡（MG/SP）与科尼隆/罗布斯塔（ES/RO）。请在上方选择品种以获得更准确的数据。",
      cacau: "可可通常以产量分成的合作方式谈判——按公顷计的固定租金很少见。",
      banana: "已成园的香蕉园按营业收入的一定比例（~15%）出租；用于新种香蕉的裸地价值低得多，且取决于水源。",
      manga: "已成园的芒果园（Vale do São Francisco，圣弗朗西斯科河谷）按收入比例出租——果价波动很大。",
      uva: "已成园的灌溉鲜食葡萄园收入高、成本也高；租金通常为收入的一定比例。",
      melao: "甜瓜是一年生作物：在 Mossoró/Açu 产区（RN/CE），企业按种植季租用裸地——拥有用水许可的灌溉土地有溢价。",
      acai: "旱地种植的阿萨伊按收入比例出租；经营管理的河漫滩阿萨伊林是另一个独立的采集市场。",
      coco: "已成园且有灌溉的矮种椰园按收入比例出租；旱作高种椰园收益低得多。",
      mamao: "木瓜周期短（约2年）：成园按收入比例出租，通常按周期签约。",
      maracuja: "百香果周期为 1,5–2 年：常见方式是合作经营或按周期出租，按收入比例计。",
      caju: "传统腰果园产量低（300–500 kg/ha 坚果）；采用 Embrapa 克隆苗更新后可达 1.600 kg/ha——老腰果园的更新合作在 CE/PI/RN 是活跃市场。",
      mandioca: "木薯是一年生作物：淀粉厂和承租户在牧场轮换地上种植（SP/PR）；东北部以家庭式木薯粉生产为主。",
      melancia: "西瓜按季种植：裸地按周期出租——Teixeira de Freitas（BA）收获 59–71 t/ha（CEPEA）。",
      abacaxi: "菠萝周期约 18 个月；通常按周期出租，灌溉地块有溢价。",
      ovinos: "在半干旱地区，天然牧场（caatinga，卡廷加旱生林）的租金远低于人工牧场；按头/月计费的合同很常见。",
      caprinos: "山羊是卡廷加地区的主力：合同按头/月计费或按牧场比例分成；人工牧场比天然牧场更值钱。",
      bufalos: "水牛集中在河漫滩与低洼地（Marajó/PA）；租金随当地牧场市场行情。",
      frango_corte: "在一体化模式中，报酬来自入栏的鸡群：成型的鸡舍才是出租的资产——裸地作用很小。",
      suinos: "一体化养猪按批次计酬；成型的猪场（设施）才是关键资产，而非裸地。",
      tilapia: "水产养殖出租的是水面：成型的水库或开挖鱼塘有自己的市场（按水面 R$/ha 计），与旱地分开。",
      camarao: "成型的对虾养殖塘（RN/CE）租金高；适合养虾的裸地取决于许可证和半咸水条件。",
      eucalipto: "人工林采用长期合同（7年以上）：固定租金或与工业企业的林业合作。",
      erva_mate: "成型的马黛茶园通常按采收出租——南部（PR/SC/RS）的传统市场。",
      fumo: "烟草采用与烟草公司的一体化模式：企业提供投入品并收购烟叶——南部经典的土地合作方式，生产者平均收入约 R$46k/ha（Afubra/CONAB，24/25 产季）。",
      mamona: "蓖麻是半干旱地区的旱作作物（BA 领先）；常与菜豆间作——按季出租。",
      limao_tahiti: "塔希提青柠有自己的市场和 CEPEA 指标（SP 占主导）；价格季节性很强——成园按收入比例出租。",
      gengibre: "生姜是一年生出口作物（ES/SC/PR）：裸地按季出租，土质轻、水源好的地块有溢价。",
      flores: "花卉业出租的是设施：成型的温室有自己的市场（Holambra/SP 和 CE 山区），与裸地分开。",
      acacia_negra: "黑荆树（RS）是周期约7年的人工林，树皮出售用于提取单宁——与工业企业签约，模式类似桉树。",
      pirarucu: "巨骨舌鱼需要大型鱼塘和许可证；RO/AM 引领养殖（Embrapa）——出租的资产是成型的鱼塘。",
      carnauba: "天然卡尔纳乌巴棕榈林本身就有收益：PI 和 CE 集中了全国约96%的卡尔纳乌巴粉，且100%产自东北部（IBGE PEVS）——按棕榈叶采收季出租。",
      babacu: "MA 约占巴巴苏仁产量的94%（IBGE PEVS）；注意多个市镇实行《自由巴巴苏法》——采集妇女的进入权受法律保护。",
      pinhao: "南部集中了全国约97%的南洋杉松子（IBGE PEVS）：天然南洋杉按采收季获益——禁止砍伐，收入来自采集。",
      castanha_amazonia: "AC 在巴西坚果产量上领先，AM 和 PA 紧随其后（IBGE PEVS）：天然坚果林按产季获益——依法禁止砍伐坚果树。2024年 PGPM-Bio 底价：R$3,66/kg（CONAB）。",
      piacava: "BA 集中了全国约96%的皮阿萨瓦纤维——Ilhéus、Nilo Peçanha 和 Cairu 领先（IBGE PEVS）；天然皮阿萨瓦林按割纤维出租。",
      pequi: "佩基果是塞拉多（cerrado）草原的立木收入（PEVS/IBGE 中 GO/MG/TO 领先）：在天然佩基林中按季采集——GO/MG 依法限制砍伐。",
      mangaba: "曼加巴是东北沿海的采集经济（SE 是 PEVS/IBGE 的参考产地）；天然曼加巴林按产季获益。",
      licuri: "利库里是巴伊亚半干旱区的棕榈（PEVS/IBGE）：在天然利库里林中采集果仁——卡廷加典型的立木收入。",
      umbu: "乌姆布是卡廷加的采集作物（PEVS/IBGE 中 BA 领先）：天然乌姆布树按产季产出果肉和甜食原料。",
      baru: "巴鲁是塞拉多正在扩张的坚果（GO/MG/MT）：在天然巴鲁树及首批种植园中采集——收购市场不断增长。",
    },
    cropFormation: {
      banana: "从种植到首次采收：约10–14个月（Embrapa）。",
      mamao: "从种植到首次采收：约8–10个月（Embrapa）。",
      maracuja: "从种植到首次采收：约7–9个月（Embrapa）。",
      uva: "从种植到首次采收：约1,5年；丰产期：约3年（Embrapa）。",
      cafe: "从种植到首次采收：约2–3年；丰产期：约4–5年（Embrapa）——种植类合同通常设有宽限期。",
      caju: "克隆矮种腰果：首次采收约2–3年；丰产期：约7年（Embrapa）——种植类合同通常设有宽限期。",
      coco: "矮种椰子：首次采收约2,5–3年；丰产期：约6年（Embrapa）——种植类合同通常设有宽限期。",
      acai: "旱地阿萨伊：首次采收约3年；丰产期：约5–6年（Embrapa）——种植类合同通常设有宽限期。",
      cacau: "从种植到首次采收：约3–4年；丰产期：约6–7年（Embrapa/CEPLAC）——种植类合同通常设有宽限期。",
      citros: "从种植到首次采收：约3年；丰产期：约7–8年（Embrapa/Fundecitrus）——种植类合同通常设有宽限期。",
      manga: "嫁接芒果：首次采收约3–4年；丰产期：约7年（Embrapa）——种植类合同通常设有宽限期。",
      dende: "从种植到首次采收：约3年；丰产期：约7–8年（Embrapa）——一体化企业通常会安排宽限期。",
      seringueira: "从种植到开始割胶：约6–7年（Embrapa）——种植类合同通常设有较长宽限期。",
      erva_mate: "从种植到首次商业修剪：约4–5年（Embrapa Florestas）。",
      eucalipto: "从种植到采伐：约6–7年（Embrapa Florestas）——因此林业合同期限较长。",
      goiaba: "克隆番石榴约1,5–2年开始结果；丰产期：约4年（Embrapa）。",
      abacate: "从种植到首次采收：约3–4年；丰产期：约7年（Embrapa）——种植类合同通常设有宽限期。",
      maca: "从种植到首次采收：约3–4年；丰产期：约5–6年（Epagri/Embrapa）——种植类合同通常设有宽限期。",
      pessego: "从种植到首次采收：约2–3年；丰产期：约4–5年（Embrapa）。",
    },
  },
  auth: {
    signIn: "登录",
    signInGoogle: "使用 Google 登录",
    signOut: "退出登录",
    myAccount: "我的账户",
    accountTitle: "我的账户",
    accountSubtitle: "您的 Palmo 账户。即将上线：您的地块信息与报价。",
    notSignedIn: "您尚未登录。登录后可保存数据并跟踪您发布的地块。",
    signedInAs: "当前登录：",
  },
  pricing: {
    eyebrow: "价格",
    title: "透明的价格",
    subtitle: "只有成交后才需付费。无月费，无发布费。",
    tiers: [
      {
        name: "发布与搜索",
        price: "免费",
        desc: "发布您的土地，浏览地块信息，沟通与谈判。双方均免费。",
      },
      {
        name: "成交服务费",
        price: "5%",
        priceNote: "按首年合同金额",
        desc: "仅在签约时收取，由租用土地的一方支付。包含标准化合同、核验与电子签名。",
        highlight: true,
      },
      {
        name: "卫星监测",
        price: "按月订阅",
        desc: "土地所有者可通过 Hexagon 卫星影像随时了解土地使用情况。可随时取消。",
      },
    ],
    footnote: "没有隐藏费用。土地所有者发布永远免费。",
  },
  waitlist: {
    eyebrow: "抢先加入",
    title: "加入候补名单",
    subtitle: "Palmo 在您的地区上线后，我们会第一时间通过 WhatsApp 通知您。",
    nameLabel: "姓名",
    namePlaceholder: "您的全名",
    phoneLabel: "WhatsApp",
    phonePlaceholder: "+55 00 00000-0000",
    countryLabel: "国家",
    stateLabel: "州",
    statePlaceholder: "例如：Bahia",
    municipalityLabel: "市镇",
    municipalityPlaceholder: "例如：Salvador",
    roleLabel: "您是……",
    rolePlaceholder: "请选择...",
    roleHave: "我有土地",
    roleWant: "我在找土地",
    purposeLabel: "土地用途",
    purposePlaceholder: "请选择用途...",
    purposeOptions: [
      { value: "graos", label: "谷物（大豆、玉米、棉花等）" },
      { value: "cana", label: "甘蔗" },
      { value: "lavoura_permanente", label: "多年生作物（咖啡、柑橘、可可等）" },
      { value: "fruticultura", label: "水果种植" },
      { value: "horticultura", label: "蔬菜园艺" },
      { value: "pecuaria_corte", label: "肉牛养殖" },
      { value: "pecuaria_leite", label: "奶业养殖" },
      { value: "avicultura_suinocultura", label: "家禽 / 生猪养殖" },
      { value: "aquicultura", label: "水产养殖" },
      { value: "silvicultura", label: "人工林（桉树、松树等）" },
      { value: "reflorestamento_carbono", label: "再造林 / 碳信用" },
      { value: "energia_solar", label: "太阳能" },
      { value: "energia_eolica", label: "风能" },
      { value: "extrativismo", label: "采集经济（立木收入）" },
      { value: "outro", label: "其他" },
    ],
    submit: "加入候补名单",
    submitting: "提交中...",
    success: "已收到！我们会通过 WhatsApp 与您联系。",
    error: "出了点问题，请稍后再试。",
  },
  footer: {
    tagline: "De palmo em palmo, a terra volta a produzir.",
    whatsapp: "通过 WhatsApp 联系",
    instagram: "Instagram",
    rights: "© 2026 Palmo. 巴西出品。",
    terms: "条款",
    privacy: "隐私",
  },
};
