// Tradução gerada por IA — sujeita a revisão nativa. Data: 2026-07-20.
// العربية الفصحى الحديثة — dicionário completo tipado a partir de content.pt.
// Invariantes: números, valores R$, unidades (ha, kg, t, sacas), percentuais,
// anos, fontes (IBGE, CONAB, Embrapa, CEPEA, PEVS...), nomes próprios,
// placeholders ({price}, {where}...) e emojis permanecem idênticos ao PT.

import { content } from "./content";

export const contentAr: typeof content.pt = {
  header: {
    navHow: "كيف تعمل المنصة",
    navTrust: "الثقة",
    navPricing: "الأسعار",
    cta: "أعلن عن أرضي",
  },
  hero: {
    title: "كل شبر من الأرض في حالة إنتاج",
    subtitle:
      "نربط أصحاب الأراضي غير المستغلة بمن يريد الإنتاج فيها — مع التحقق والعقد والمتابعة.",
    ctaHave: "لديّ أرض",
    ctaWant: "أبحث عن أرض",
    trustLine: "مجاني حتى إتمام الصفقة",
    card: {
      photoLabel: "صورة جوية للمزرعة",
      name: "Fazenda Boa Vista",
      area: "128 ha",
      location: "Rio Verde, GO",
      verified: "موثَّق",
    },
  },
  how: {
    eyebrow: "كيف تعمل المنصة",
    title: "من الإعلان إلى التوقيع في ثلاث خطوات",
    steps: [
      {
        title: "أعلن مع التحقق",
        desc: "تُراجَع مستندات الأرض وبياناتها قبل النشر.",
      },
      {
        title: "اعثر على الشريك المثالي",
        desc: "منتجون، ومربّو ماشية، ومشاريع طاقة شمسية وإعادة تشجير يتواصلون معك. تتحاور وتقارن.",
      },
      {
        title: "أتمم الصفقة بأمان",
        desc: "عقد موحَّد، وتوقيع رقمي، وتقارير متابعة دورية.",
      },
    ],
  },
  trust: {
    eyebrow: "الثقة",
    title: "مصمَّم لتوفير الأمان للطرفين",
    badges: [
      {
        title: "إعلانات موثَّقة",
        desc: "كل أرض تُنشر تخضع لفحص المستندات وسجل CAR (السجل البيئي الريفي).",
      },
      {
        title: "عقود موحَّدة",
        desc: "نماذج راجعها محامون متخصصون في القطاع الزراعي، ببنود واضحة للإيجار أو الشراكة.",
      },
      {
        title: "متابعة عبر الأقمار الاصطناعية",
        desc: "يتلقى المالك تقارير دورية توضح كيفية استخدام أرضه.",
      },
    ],
  },
  appraiser: {
    navLabel: "كم تساوي أرضي",
    eyebrow: "الحاسبة",
    title: "كم تساوي أرضك غير المستغلة؟",
    subtitle: "اكتشف في 1 دقيقة نطاق قيم الإيجار المعمول بها في منطقتك.",
    stateLabel: "الولاية",
    municipalityLabel: "البلدية",
    municipalityPlaceholder: "اختر البلدية...",
    municipalitySelectState: "اختر الولاية أولاً",
    municipalityLoading: "جارٍ تحميل البلديات...",
    hectaresLabel: "المساحة (بالهكتار ha)",
    hectaresPlaceholder: "مثال: 128",
    purposeLabel: "استخدام الأرض",
    purposePlaceholder: "اختر الاستخدام...",
    submit: "احسب القيمة",
    resultTitle: "النطاق المرجعي لأرضك",
    perHaYear: "لكل هكتار/سنة",
    totalForArea: "لمساحتك، ما يقارب",
    consultTitle: "هذا السوق متخصص جدًا",
    consultBody:
      "بالنسبة لهذا الاستخدام، تتفاوت القيم كثيرًا بين المناطق بحيث لا يمكن تقديم نطاق موثوق. اترك بيانات الاتصال وسنخبرك عند توفر عروض حقيقية في منطقتك.",
    consultPickCrop:
      "نصيحة: اختر المحصول المحدد في الحقل أعلاه — لدينا مراجع سوقية لمنطقتك لعدة محاصيل (الموز، الأسائي açaí، الكاكاو...).",
    consultPotential:
      "إمكانات مساحتك مع {use} — الاستخدام الأعلى قيمة الذي تتوفر له مراجع في منطقتك:",
    disclaimer:
      "قيم مرجعية مستندة إلى مصادر سوقية عامة (النقابات الريفية وIMEA وCNA وشركات الاستشارات). لا تشكّل تقييمًا رسميًا — فالقيمة الفعلية تعتمد على التربة واللوجستيات والمياه والتفاوض.",
    legalNote:
      "بموجب القانون البرازيلي (Estatuto da Terra — قانون الأراضي)، يُحدَّد سقف الإيجار الزراعي بنسبة 15% من قيمة العقار سنويًا (30% في مناطق الاستغلال المكثف).",
    leadTitle: "هل تريد تلقي عروض حقيقية ضمن هذا النطاق؟",
    leadSubtitle: "انضم إلى قائمة الانتظار — مجانًا.",
    heroLink: "كم تساوي أرضي؟",
    heroLinkSub: "اكتشف ذلك في 30 ثانية — مجانًا وببيانات رسمية.",
    compareTitle: "استخدامات أخرى في منطقتك",
    compareUnit: "/ha/سنة",
    compareYourChoice: "اختيارك",
    compareUpsell:
      "في منطقتك، تصل إيجارات الأراضي المخصصة لـ {use} إلى {ratio}x قيمة اختيارك الحالي.",
    compareCaveat:
      "تعتمد هذه المقارنة على نطاقات سوقية إقليمية. أما مدى ملاءمة استخدام أعلى قيمة لأرضك فيعتمد على التربة والتضاريس والمياه واللوجستيات — ويمكن لـ Palmo مساعدتك في التحقق من ذلك.",
    selectiveTag: "سوق انتقائي — يعتمد على المشاريع وشبكة الكهرباء في المنطقة",
    cropLabel: "المحصول المحدد (اختياري)",
    cropPlaceholder: "الكل / لا أعرف بعد",
    cropRefPotential:
      "تقدير مبني على القيمة السوقية لـ {source} — R$ {landMin} إلى {landMax} ألف/ha — محوَّلة بنسبة 2,5–6% سنويًا:",
    formedPotential:
      "مع مزرعة قائمة ومنتِجة: في منطقتك، تبلغ الإيجارات عادةً نحو ~15% من الإيرادات ({source}):",
    formedNote:
      "ينطبق على محصول مزروع ومنتِج بالفعل. الأرض الجرداء (بدون الزراعة القائمة) تساوي أقل بكثير — انظر أدناه.",
    formedMath:
      "🧮 الحساب: إيرادات مقدَّرة من {revMin} إلى {revMax} لكل هكتار/سنة × ~15% (العرف السوقي للمزارع القائمة) = النطاق أعلاه.",
    nationalFallbackNote:
      "⚠️ مرجع وطني واسع — لا يملك ولايتك بعد نطاقًا خاصًا مستطلَعًا لهذا الاستخدام؛ اعتبره حدًا أدنى وأعلى واسعين.",
    cropVariants: {
      cafe: [
        { value: "arabica", label: "أرابيكا" },
        { value: "conilon", label: "كونيلون / روبوستا" },
      ],
      uva: [
        { value: "mesa", label: "عنب المائدة" },
        { value: "vinho_suco", label: "النبيذ والعصير" },
      ],
      banana: [
        { value: "prata", label: "براتا (Prata)" },
        { value: "nanica", label: "كافنديش (Nanica)" },
        { value: "terra", label: "موز الجنة (Da terra)" },
      ],
    },
    variantLabel: "الصنف (اختياري)",
    variantPlaceholder: "الكل / لا أعرف",
    pevsPriceLine:
      "💰 متوسط السعر المدفوع للمنتِج {where}: {price}/kg (IBGE PEVS {year}).",
    pevsWhereMuni: "في بلديتك",
    pevsWhereUf: "في ولايتك",
    pevsWhereBr: "في البرازيل",
    pevsHint:
      "الدخل من الأشجار القائمة = كثافة أشجارك × الإنتاج × هذا السعر. وبرنامج PGPM-Bio (CONAB) يضمن حدًا أدنى للسعر — فإذا بعت بأقل من الحد الأدنى، تدفع CONAB الفرق.",
    rawLandLabel: "الأرض الجرداء (بدون زراعة قائمة):",
    advantageLabel: "ميزة إقليمية",
    vtnPotential:
      "تقدير وفق القيمة الرسمية للأرض في بلديتك (VTN {year} من مصلحة الضرائب الفيدرالية Receita Federal × 2,5–6% سنويًا):",
    vtnPotentialApprox:
      "لم تبلّغ بلديتك عن قيمة VTN إلى Receita Federal. تقدير وفق المتوسط الرسمي لولايتك (VTN {year} × 2,5–6% سنويًا):",
    vtnLine:
      "القيمة الرسمية للأرض (VTN {year}، Receita Federal) في بلديتك: {value}/ha.",
    vtnLineApprox:
      "المتوسط الرسمي للأرض في ولايتك (VTN {year}، Receita Federal): {value}/ha — لم تبلّغ بلديتك عن قيمة خاصة بها.",
    crops: {
      graos: [
        { value: "soja", label: "فول الصويا" },
        { value: "milho", label: "الذرة" },
        { value: "algodao", label: "القطن" },
        { value: "arroz", label: "الأرز المروي" },
        { value: "feijao", label: "الفاصوليا" },
        { value: "sorgo", label: "الذرة الرفيعة" },
        { value: "trigo", label: "القمح" },
        { value: "girassol", label: "عباد الشمس" },
        { value: "amendoim", label: "الفول السوداني" },
        { value: "gergelim", label: "السمسم" },
        { value: "aveia", label: "الشوفان" },
        { value: "cevada", label: "الشعير" },
        { value: "canola", label: "الكانولا" },
        { value: "milheto", label: "الدخن" },
        { value: "grao_de_bico", label: "الحمص" },
        { value: "mamona", label: "الخروع" },
        { value: "fumo", label: "التبغ" },
        { value: "fava", label: "الفول" },
        { value: "chia", label: "بذور الشيا" },
        { value: "triticale", label: "التريتيكالي" },
      ],
      lavoura_permanente: [
        { value: "cafe", label: "البن" },
        { value: "cacau", label: "الكاكاو" },
        { value: "caju", label: "الكاجو" },
        { value: "citros", label: "الحمضيات (البرتقال)" },
        { value: "seringueira", label: "شجرة المطاط" },
        { value: "dende", label: "نخيل الزيت" },
        { value: "erva_mate", label: "المتة (erva-mate)" },
        { value: "pimenta_do_reino", label: "الفلفل الأسود" },
        { value: "guarana", label: "الغوارانا (guaraná)" },
        { value: "macadamia", label: "المكاداميا" },
        { value: "noz_pecan", label: "البيكان" },
        { value: "oliveira", label: "الزيتون (زيت)" },
        { value: "palmito_pupunha", label: "قلب نخيل بوبونيا (pupunha)" },
        { value: "urucum", label: "الأناتو (urucum)" },
        { value: "limao_tahiti", label: "ليمون تاهيتي" },
        { value: "aroeira", label: "الفلفل الوردي (aroeira)" },
      ],
      fruticultura: [
        { value: "banana", label: "الموز" },
        { value: "manga", label: "المانجو" },
        { value: "uva", label: "العنب" },
        { value: "melao", label: "الشمام" },
        { value: "acai", label: "الأسائي (açaí)" },
        { value: "coco", label: "جوز الهند" },
        { value: "mamao", label: "البابايا" },
        { value: "maracuja", label: "فاكهة العاطفة (ماراكويا)" },
        { value: "melancia", label: "البطيخ" },
        { value: "abacaxi", label: "الأناناس" },
        { value: "goiaba", label: "الجوافة" },
        { value: "acerola", label: "الأسيرولا" },
        { value: "abacate", label: "الأفوكادو" },
        { value: "atemoia", label: "القشطة والأتيمويا" },
        { value: "graviola", label: "القشطة الشائكة (غرافيولا)" },
        { value: "pitaya", label: "فاكهة التنين (بيتايا)" },
        { value: "morango", label: "الفراولة" },
        { value: "maca", label: "التفاح" },
        { value: "pessego", label: "الخوخ (الدرّاق)" },
        { value: "tangerina", label: "اليوسفي" },
        { value: "cupuacu", label: "كوبواسو (cupuaçu)" },
        { value: "roma", label: "الرمان" },
        { value: "lichia", label: "الليتشي" },
        { value: "figo", label: "التين" },
        { value: "caqui", label: "الكاكا (البرسيمون)" },
        { value: "jabuticaba", label: "جابوتيكابا (jabuticaba)" },
      ],
      horticultura: [
        { value: "hortalicas", label: "خضروات متنوعة" },
        { value: "mandioca", label: "الكسافا" },
        { value: "batata", label: "البطاطس" },
        { value: "batata_doce", label: "البطاطا الحلوة" },
        { value: "tomate", label: "الطماطم" },
        { value: "cebola", label: "البصل" },
        { value: "alho", label: "الثوم" },
        { value: "cenoura", label: "الجزر" },
        { value: "abobora", label: "اليقطين" },
        { value: "pimentao", label: "الفلفل الحلو" },
        { value: "inhame", label: "اليام (inhame)" },
        { value: "quiabo", label: "البامية" },
        { value: "gengibre", label: "الزنجبيل" },
        { value: "pimentas", label: "الفلفل الحار (للمُعلَّبات)" },
        { value: "mandioquinha", label: "أراكاتشا (mandioquinha)" },
        { value: "brassicas", label: "الكرنبيات (الملفوف، البروكلي...)" },
        { value: "beterraba", label: "الشمندر" },
        { value: "chuchu", label: "الشايوت" },
        { value: "pepino", label: "الخيار" },
        { value: "flores", label: "الزهور ونباتات الزينة" },
      ],
      pecuaria_corte: [
        { value: "bovinos_corte", label: "أبقار اللحم" },
        { value: "ovinos", label: "الأغنام" },
        { value: "caprinos", label: "الماعز" },
        { value: "bufalos", label: "الجاموس" },
      ],
      pecuaria_leite: [
        { value: "bovino_leite", label: "أبقار الحليب" },
        { value: "caprino_leite", label: "ماعز الحليب" },
      ],
      avicultura_suinocultura: [
        { value: "frango_corte", label: "دجاج اللحم (نظام التكامل)" },
        { value: "postura", label: "الدجاج البيّاض (بيض)" },
        { value: "suinos", label: "الخنازير (نظام التكامل)" },
      ],
      aquicultura: [
        { value: "tilapia", label: "البلطي" },
        { value: "camarao", label: "تربية الروبيان" },
        { value: "tambaqui", label: "تامباكي (tambaqui)" },
        { value: "pirarucu", label: "بيراروكو (pirarucu)" },
      ],
      silvicultura: [
        { value: "eucalipto", label: "الأوكالبتوس" },
        { value: "pinus", label: "الصنوبر" },
        { value: "teca", label: "الساج" },
        { value: "mogno_africano", label: "الماهوغني الأفريقي" },
        { value: "acacia_negra", label: "الأكاسيا السوداء (التانين)" },
        { value: "parica", label: "باريكا (paricá)" },
        { value: "cedro_australiano", label: "الأرز الأسترالي" },
        { value: "bambu", label: "الخيزران" },
      ],
      extrativismo: [
        { value: "carnauba", label: "كارناوبا (carnaúba — مسحوق وشمع)" },
        { value: "babacu", label: "باباسو (babaçu)" },
        { value: "pinhao", label: "صنوبر الأروكاريا (pinhão)" },
        { value: "castanha_amazonia", label: "جوز البرازيل" },
        { value: "piacava", label: "بياسافا (piaçava — ألياف)" },
        { value: "pequi", label: "بيكي (pequi)" },
        { value: "mangaba", label: "مانغابا (mangaba)" },
        { value: "licuri", label: "ليكوري (licuri)" },
        { value: "umbu", label: "أومبو (umbu)" },
        { value: "baru", label: "بارو (baru)" },
      ],
    },
    cropNotes: {
      soja: "تُحدَّد عقود الحبوب عادةً بعدد أكياس (sacas) فول الصويا لكل هكتار/سنة.",
      milho: "حتى بالنسبة للذرة، تُحدَّد العقود عادةً بأكياس (sacas) فول الصويا لكل هكتار/سنة (تناوب صويا/ذرة).",
      algodao: "الأراضي الملائمة للقطن تُتفاوَض عادةً عند أعلى نطاق الحبوب في المنطقة.",
      arroz: "للأرز المروي سوقه الخاصة: عادةً 18–25 كيسًا (sacas) من الأرز/ha/سنة مقابل الأرض والمياه (مرجع RS).",
      cafe: "يُتفاوَض على البن عادةً بنظام الشراكة (المناصفة) لا بإيجار ثابت — وهما سوقان بأسعار مختلفة جدًا: أرابيكا (MG/SP) وكونيلون/روبوستا (ES/RO). حدِّد الصنف أعلاه للحصول على بيانات أفضل.",
      cacau: "يُتفاوَض على الكاكاو عادةً بنظام الشراكة مع تقاسم الإنتاج — والإيجارات الثابتة لكل هكتار نادرة.",
      banana: "مزرعة الموز القائمة تُؤجَّر بنسبة من الإيرادات (~15%)؛ أما الأرض الجرداء لزراعة الموز فتساوي أقل بكثير وتعتمد على المياه.",
      manga: "بستان المانجو القائم (Vale do São Francisco) يُؤجَّر بنسبة من الإيرادات — وسعر الفاكهة شديد التقلب.",
      uva: "كرم عنب المائدة المروي القائم ذو إيرادات عالية وتكاليف عالية؛ ويكون الإيجار عادةً نسبة من الإيرادات.",
      melao: "الشمام محصول سنوي: في قطب Mossoró/Açu (RN/CE) تستأجر الشركات الأرض الجرداء لكل موسم — وللأرض المروية ذات حقوق المياه علاوة سعرية.",
      acai: "الأسائي المزروع في الأراضي المرتفعة يُؤجَّر بنسبة من الإيرادات؛ أما أسائي السهول الفيضية المُدار فهو سوق استخراجية مستقلة.",
      coco: "مزرعة جوز الهند القزم القائمة والمروية تُؤجَّر بنسبة من الإيرادات؛ ومزارع جوز الهند العملاق البعلية تدرّ أقل بكثير.",
      mamao: "البابايا دورتها قصيرة (~2 سنة): المزرعة القائمة تُؤجَّر بنسبة من الإيرادات، وعادةً بعقود لكل دورة.",
      maracuja: "دورة فاكهة العاطفة 1,5–2 سنة: الشائع هو الشراكة أو الإيجار لكل دورة بنسبة من الإيرادات.",
      caju: "بساتين الكاجو التقليدية قليلة الإنتاج (300–500 kg/ha من الجوز)؛ وبالتجديد بسلالات Embrapa المستنسخة تصل إلى 1.600 kg/ha — وشراكات تجديد البساتين القديمة سوق نشطة في CE/PI/RN.",
      mandioca: "الكسافا محصول سنوي: مصانع النشا والمستأجرون يزرعونها في أراضي تجديد المراعي (SP/PR)؛ وفي الشمال الشرقي يغلب الإنتاج العائلي للدقيق.",
      melancia: "البطيخ محصول موسمي: تُؤجَّر الأرض الجرداء لكل دورة — تحصد Teixeira de Freitas (BA) نحو 59–71 t/ha (CEPEA).",
      abacaxi: "دورة الأناناس نحو 18 شهرًا؛ والشائع هو الإيجار لكل دورة مع علاوة للأراضي المروية.",
      ovinos: "في المناطق شبه القاحلة، تُؤجَّر المراعي الطبيعية (كاتينغا caatinga) بأقل بكثير من المراعي المزروعة؛ والعقود لكل رأس/شهر شائعة.",
      caprinos: "الماعز يهيمن على الكاتينغا: عقود لكل رأس/شهر أو نسبة من المرعى؛ والمرعى المزروع أعلى قيمة من الطبيعي.",
      bufalos: "يتركز الجاموس في السهول الفيضية والمنخفضات (Marajó/PA)؛ ويتبع الإيجار سوق المراعي في المنطقة.",
      frango_corte: "في نظام التكامل، الدفعة المسكَّنة هي التي تدفع: حظيرة الدواجن الجاهزة هي الأصل المؤجَّر — والأرض الجرداء وزنها ضئيل.",
      suinos: "تربية الخنازير المتكاملة تدفع لكل دفعة؛ والمنشأة الجاهزة هي الأصل المهم، لا الأرض الجرداء.",
      tilapia: "الاستزراع المائي يؤجّر سطح المياه: للسد أو الحوض المحفور الجاهز سوقه الخاصة (R$/ha من المياه)، منفصلة عن الأرض الجافة.",
      camarao: "أحواض الروبيان الجاهزة (RN/CE) تُؤجَّر بأسعار مرتفعة؛ والأرض الجرداء الملائمة لتربية الروبيان تعتمد على الترخيص والمياه شبه المالحة.",
      eucalipto: "الغابات المزروعة تعتمد عقودًا طويلة (7+ سنوات): إيجار ثابت أو شراكة حرجية مع الصناعة.",
      erva_mate: "حقل المتة القائم يُؤجَّر عادةً لكل حصاد — سوق تقليدية في الجنوب (PR/SC/RS).",
      fumo: "التبغ يعمل بنظام التكامل مع شركات التبغ: تموّل الشركة المدخلات وتشتري المحصول — شراكة الأراضي الكلاسيكية في الجنوب، بدخل متوسط للمنتِج نحو R$46k/ha (Afubra/CONAB، موسم 24/25).",
      mamona: "الخروع محصول بعلي في المناطق شبه القاحلة (BA في الصدارة)؛ وغالبًا ما يُزرع بالتداخل مع الفاصوليا — إيجار لكل موسم.",
      limao_tahiti: "لليمون تاهيتي سوقه ومؤشر CEPEA الخاص به (SP تهيمن)؛ والسعر موسمي بقوة — البستان القائم يُؤجَّر بنسبة من الإيرادات.",
      gengibre: "الزنجبيل محصول تصديري سنوي (ES/SC/PR): تُؤجَّر الأرض الجرداء لكل موسم، مع علاوة للتربة الخفيفة والمياه.",
      flores: "زراعة الزهور تؤجّر البنية: للبيت المحمي الجاهز سوقه الخاصة (Holambra/SP ومرتفعات CE)، منفصلة عن الأرض الجرداء.",
      acacia_negra: "الأكاسيا السوداء (RS) غابة دورتها نحو 7 سنوات يُباع لحاؤها لاستخراج التانين — عقود مع الصناعة، مثل الأوكالبتوس.",
      pirarucu: "بيراروكو يتطلب أحواضًا كبيرة وترخيصًا؛ RO/AM تتصدران التربية (Embrapa) — والأصل المؤجَّر هو الحوض الجاهز.",
      carnauba: "غابة الكارناوبا الطبيعية القائمة تدرّ دخلاً بذاتها: تتركّز في PI وCE نحو 96% من مسحوق الكارناوبا في البلاد، و100% منه من الشمال الشرقي (IBGE PEVS) — ويُؤجَّر الاستخراج لكل موسم سعف.",
      babacu: "تمثّل MA نحو 94% من لوز الباباسو (IBGE PEVS)؛ انتبه إلى قانون الباباسو الحر في عدة بلديات — حق وصول جامعات الثمار محمي.",
      pinhao: "يتركّز في الجنوب نحو 97% من صنوبر الأروكاريا الوطني (IBGE PEVS): أشجار الأروكاريا الطبيعية القائمة تدرّ لكل حصاد — القطع محظور، والدخل من الجمع.",
      castanha_amazonia: "تتصدر AC إنتاج جوز البرازيل، تليها AM وPA (IBGE PEVS): الغابات الطبيعية تدرّ لكل موسم — وقطع الشجرة محظور قانونًا. الحد الأدنى لبرنامج PGPM-Bio لعام 2024: R$3,66/kg (CONAB).",
      piacava: "تتركّز في BA نحو 96% من ألياف البياسافا في البلاد — تتصدر Ilhéus وNilo Peçanha وCairu (IBGE PEVS)؛ وتُؤجَّر الغابات الطبيعية لكل قطع للألياف.",
      pequi: "البيكي دخل من الأشجار القائمة في السرادو (GO/MG/TO في PEVS/IBGE): جمع موسمي من الأشجار الطبيعية — وقطع الشجرة مقيَّد قانونًا في GO/MG.",
      mangaba: "المانغابا نشاط استخراجي على ساحل الشمال الشرقي (SE هي المرجع في PEVS/IBGE)؛ والأشجار الطبيعية تدرّ لكل موسم.",
      licuri: "الليكوري نخلة المناطق شبه القاحلة في باهيا (PEVS/IBGE): تُجمع اللوزات من الأشجار الطبيعية — دخل قائم نموذجي للكاتينغا.",
      umbu: "الأومبو جمع من الكاتينغا (BA تتصدر في PEVS/IBGE): أشجار الأومبو الطبيعية تدرّ لكل موسم لصناعة اللب والحلويات.",
      baru: "البارو جوزة السرادو الآخذة في التوسع (GO/MG/MT): جمع من الأشجار الطبيعية وأولى المزارع — وسوق المشترين في نمو.",
    },
    cropFormation: {
      banana: "من الزراعة إلى أول حصاد: نحو 10–14 شهرًا (Embrapa).",
      mamao: "من الزراعة إلى أول حصاد: نحو 8–10 أشهر (Embrapa).",
      maracuja: "من الزراعة إلى أول حصاد: نحو 7–9 أشهر (Embrapa).",
      uva: "من الزراعة إلى أول حصاد: نحو 1,5 سنة؛ الإنتاج الكامل: نحو 3 سنوات (Embrapa).",
      cafe: "من الزراعة إلى أول حصاد: نحو 2–3 سنوات؛ الإنتاج الكامل: نحو 4–5 سنوات (Embrapa) — عقود الزراعة تتضمن عادةً فترة سماح.",
      caju: "الكاجو القزم المستنسخ: أول حصاد نحو 2–3 سنوات؛ الإنتاج الكامل: نحو 7 سنوات (Embrapa) — عقود الزراعة تتضمن عادةً فترة سماح.",
      coco: "جوز الهند القزم: أول حصاد نحو 2,5–3 سنوات؛ الإنتاج الكامل: نحو 6 سنوات (Embrapa) — عقود الزراعة تتضمن عادةً فترة سماح.",
      acai: "أسائي الأراضي المرتفعة: أول حصاد نحو 3 سنوات؛ الإنتاج الكامل: نحو 5–6 سنوات (Embrapa) — عقود الزراعة تتضمن عادةً فترة سماح.",
      cacau: "من الزراعة إلى أول حصاد: نحو 3–4 سنوات؛ الإنتاج الكامل: نحو 6–7 سنوات (Embrapa/CEPLAC) — عقود الزراعة تتضمن عادةً فترة سماح.",
      citros: "من الزراعة إلى أول حصاد: نحو 3 سنوات؛ الإنتاج الكامل: نحو 7–8 سنوات (Embrapa/Fundecitrus) — عقود الزراعة تتضمن عادةً فترة سماح.",
      manga: "المانجو المطعَّم: أول حصاد نحو 3–4 سنوات؛ الإنتاج الكامل: نحو 7 سنوات (Embrapa) — عقود الزراعة تتضمن عادةً فترة سماح.",
      dende: "من الزراعة إلى أول حصاد: نحو 3 سنوات؛ الإنتاج الكامل: نحو 7–8 سنوات (Embrapa) — شركات التكامل عادةً ما تنظّم فترة السماح.",
      seringueira: "من الزراعة إلى بدء التسييل (جمع المطاط): نحو 6–7 سنوات (Embrapa) — عقود الزراعة تتضمن عادةً فترة سماح طويلة.",
      erva_mate: "من الزراعة إلى أول تقليم تجاري: نحو 4–5 سنوات (Embrapa Florestas).",
      eucalipto: "من الزراعة إلى القطع: نحو 6–7 سنوات (Embrapa Florestas) — ولهذا تكون العقود الحرجية طويلة.",
      goiaba: "الجوافة المستنسخة تثمر بدءًا من نحو 1,5–2 سنة؛ الإنتاج الكامل: نحو 4 سنوات (Embrapa).",
      abacate: "من الزراعة إلى أول حصاد: نحو 3–4 سنوات؛ الإنتاج الكامل: نحو 7 سنوات (Embrapa) — عقود الزراعة تتضمن عادةً فترة سماح.",
      maca: "من الزراعة إلى أول حصاد: نحو 3–4 سنوات؛ الإنتاج الكامل: نحو 5–6 سنوات (Epagri/Embrapa) — عقود الزراعة تتضمن عادةً فترة سماح.",
      pessego: "من الزراعة إلى أول حصاد: نحو 2–3 سنوات؛ الإنتاج الكامل: نحو 4–5 سنوات (Embrapa).",
    },
  },
  auth: {
    signIn: "تسجيل الدخول",
    signInGoogle: "تسجيل الدخول عبر Google",
    signOut: "تسجيل الخروج",
    myAccount: "حسابي",
    accountTitle: "حسابي",
    accountSubtitle: "حسابك في Palmo. قريبًا: إعلاناتك وعروضك.",
    notSignedIn: "لم تسجّل الدخول بعد. سجّل الدخول لحفظ بياناتك ومتابعة إعلاناتك.",
    signedInAs: "متصل باسم",
  },
  pricing: {
    eyebrow: "الأسعار",
    title: "أسعار شفافة",
    subtitle: "لا تدفع إلا عند إتمام الصفقة. بلا اشتراك شهري وبلا رسوم إعلان.",
    tiers: [
      {
        name: "الإعلان والبحث",
        price: "مجاني",
        desc: "سجّل أرضك، وتصفّح الإعلانات، وتحاور وتفاوض. مجانًا للطرفين.",
      },
      {
        name: "عمولة النجاح",
        price: "5%",
        priceNote: "من قيمة السنة الأولى للعقد",
        desc: "تُحصَّل عند التوقيع فقط ويدفعها من سيُنتج في الأرض. تشمل العقد الموحَّد والتحقق والتوقيع الرقمي.",
        highlight: true,
      },
      {
        name: "المراقبة عبر الأقمار الاصطناعية",
        price: "اشتراك شهري",
        desc: "ليتابع المالك كيفية استخدام أرضه عبر صور الأقمار الاصطناعية من Hexagon. يمكن الإلغاء في أي وقت.",
      },
    ],
    footnote: "لا رسوم خفية. المالك لا يدفع أبدًا مقابل الإعلان.",
  },
  waitlist: {
    eyebrow: "كن من الأوائل",
    title: "انضم إلى قائمة الانتظار",
    subtitle: "سنخبرك عبر WhatsApp فور انطلاق Palmo في منطقتك.",
    nameLabel: "الاسم",
    namePlaceholder: "اسمك الكامل",
    phoneLabel: "WhatsApp",
    phonePlaceholder: "+55 00 00000-0000",
    countryLabel: "الدولة",
    stateLabel: "الولاية",
    statePlaceholder: "مثال: Bahia",
    municipalityLabel: "البلدية",
    municipalityPlaceholder: "مثال: Salvador",
    roleLabel: "أنت...",
    rolePlaceholder: "اختر...",
    roleHave: "لديّ أرض",
    roleWant: "أبحث عن أرض",
    purposeLabel: "الغرض من استخدام الأرض",
    purposePlaceholder: "اختر الغرض...",
    purposeOptions: [
      { value: "graos", label: "الحبوب (صويا، ذرة، قطن...)" },
      { value: "cana", label: "قصب السكر" },
      { value: "lavoura_permanente", label: "المحاصيل الدائمة (بن، حمضيات، كاكاو...)" },
      { value: "fruticultura", label: "زراعة الفواكه" },
      { value: "horticultura", label: "البستنة والخضروات" },
      { value: "pecuaria_corte", label: "تربية أبقار اللحم" },
      { value: "pecuaria_leite", label: "تربية أبقار الحليب" },
      { value: "avicultura_suinocultura", label: "الدواجن / الخنازير" },
      { value: "aquicultura", label: "الاستزراع المائي" },
      { value: "silvicultura", label: "الغابات المزروعة (أوكالبتوس، صنوبر...)" },
      { value: "reflorestamento_carbono", label: "إعادة التشجير / أرصدة الكربون" },
      { value: "energia_solar", label: "الطاقة الشمسية" },
      { value: "energia_eolica", label: "طاقة الرياح" },
      { value: "extrativismo", label: "الاستخراج (دخل الأشجار القائمة)" },
      { value: "outro", label: "أخرى" },
    ],
    submit: "أريد الانضمام إلى القائمة",
    submitting: "جارٍ الإرسال...",
    success: "تم الاستلام! سنتواصل معك عبر WhatsApp.",
    error: "حدث خطأ ما. حاول مرة أخرى بعد قليل.",
  },
  footer: {
    tagline: "De palmo em palmo, a terra volta a produzir.",
    whatsapp: "تواصل عبر WhatsApp",
    instagram: "Instagram",
    rights: "© 2026 Palmo. صُنع في البرازيل.",
    terms: "الشروط",
    privacy: "الخصوصية",
  },
};
