/**
 * Official land-value (VTN) layer for the calculator.
 *
 * lib/vtn-data.json is generated by scripts/ingest-vtn.mjs from the Receita
 * Federal's annual "Valores de Terra Nua" table (land value per municipality
 * × aptitude, per IN RFB 1.877/2019). Until the ingest script has been run,
 * the file is an empty placeholder and every lookup returns null.
 *
 * Lease derivation: rural leases in Brazil typically run 2.5%–6% of the
 * land's value per year (with a legal ceiling of 15% under the Estatuto da
 * Terra). We apply that band to the municipality's official VTN for the
 * aptitude matching the chosen land use.
 */
import vtnJson from "./vtn-data.json";

type VtnRow = {
  boa: number | null;
  regular: number | null;
  restrita: number | null;
  pastagem: number | null;
  silvicultura: number | null;
};

const DATA = (vtnJson as { year: number; data: Record<string, VtnRow> }) ?? {
  year: 0,
  data: {},
};

export const VTN_YEAR = DATA.year;

const LOW = 0.025; // 2.5% of land value / year
const HIGH = 0.06; // 6% of land value / year

function normalizeName(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toUpperCase()
    .replace(/[^A-Z0-9 ]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Which VTN aptitude column applies to each land-use category. */
function fieldFor(purpose: string): keyof VtnRow | null {
  switch (purpose) {
    case "graos":
    case "cana":
    case "horticultura":
    case "fruticultura":
    case "lavoura_permanente":
      return "boa";
    case "pecuaria_corte":
    case "pecuaria_leite":
      return "pastagem";
    case "silvicultura":
    case "reflorestamento_carbono":
      return "silvicultura";
    default:
      return null; // solar/eólica/aquicultura/outro: land value isn't the driver
  }
}

export type VtnEstimate = {
  vtnPerHa: number;
  minPerHa: number;
  maxPerHa: number;
  year: number;
};

export function estimateFromVTN(
  uf: string,
  municipality: string,
  purpose: string,
): VtnEstimate | null {
  if (!DATA.year) return null;
  const row = DATA.data[`${uf}|${normalizeName(municipality)}`];
  if (!row) return null;
  const field = fieldFor(purpose);
  if (!field) return null;
  // fall back through aptitude tiers if the ideal one wasn't reported
  const vtn =
    row[field] ??
    (field === "boa" ? row.regular ?? row.restrita : null) ??
    null;
  if (!vtn) return null;
  return {
    vtnPerHa: vtn,
    minPerHa: Math.round(vtn * LOW),
    maxPerHa: Math.round(vtn * HIGH),
    year: DATA.year,
  };
}
