/**
 * Official land-value (VTN) layer for the calculator.
 *
 * lib/vtn-data.json is generated by scripts/ingest-vtn.mjs from the Receita
 * Federal's annual "Valores de Terra Nua" tables (land value per municipality
 * × aptitude, per IN RFB 1.877/2019), merged across publication years
 * (newest wins) and including computed official state averages as fallback.
 *
 * Lease derivation: rural leases typically run 2.5%–6% of land value per
 * year (legal ceiling: 15%, Estatuto da Terra).
 */
import vtnJson from "./vtn-data.json";

type VtnRow = {
  boa: number | null;
  regular: number | null;
  restrita: number | null;
  pastagem: number | null;
  silvicultura: number | null;
  /** source publication year for this municipality (v2 files) */
  y?: number;
};

type VtnFile = {
  year: number;
  data: Record<string, VtnRow>;
  ufAvg?: Record<string, Partial<Record<keyof VtnRow, number | null>>>;
};

const DATA = (vtnJson as VtnFile) ?? { year: 0, data: {} };

export const VTN_YEAR = DATA.year;

const LOW = 0.025; // 2.5% of land value / year
const HIGH = 0.06; // 6% of land value / year

function normalizeName(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toUpperCase()
    .replace(/[^A-Z0-9 ]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Which VTN aptitude column applies to each land-use category. */
function fieldFor(purpose: string): keyof VtnRow | null {
  switch (purpose) {
    case "graos":
    case "cana":
    case "horticultura":
    case "fruticultura":
    case "lavoura_permanente":
      return "boa";
    case "pecuaria_corte":
    case "pecuaria_leite":
      return "pastagem";
    case "silvicultura":
    case "reflorestamento_carbono":
      return "silvicultura";
    default:
      return null; // solar/eólica/aquicultura/outro: land value isn't the driver
  }
}

export type VtnEstimate = {
  vtnPerHa: number;
  minPerHa: number;
  maxPerHa: number;
  year: number;
  /** true when derived from the official STATE AVERAGE, not the municipality */
  approx: boolean;
};

export function estimateFromVTN(
  uf: string,
  municipality: string,
  purpose: string,
): VtnEstimate | null {
  if (!DATA.year) return null;
  const field = fieldFor(purpose);
  if (!field) return null;

  const row = DATA.data[`${uf}|${normalizeName(municipality)}`];
  if (row) {
    const vtn =
      row[field] ??
      (field === "boa" ? row.regular ?? row.restrita : null) ??
      null;
    if (vtn && typeof vtn === "number") {
      return {
        vtnPerHa: vtn,
        minPerHa: Math.round(vtn * LOW),
        maxPerHa: Math.round(vtn * HIGH),
        year: row.y ?? DATA.year,
        approx: false,
      };
    }
  }

  // Fallback: official state average from the same dataset
  const avg = DATA.ufAvg?.[uf]?.[field];
  if (avg && typeof avg === "number") {
    return {
      vtnPerHa: avg,
      minPerHa: Math.round(avg * LOW),
      maxPerHa: Math.round(avg * HIGH),
      year: DATA.year,
      approx: true,
    };
  }
  return null;
}
